version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      capacitor:
        patterns: ['@capacitor/*']
      frontend:
        patterns: ['react*', 'vite', '@vitejs/*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
